"""Independent readback of the delivered editor v1 ROM (FINAL-01). Software/CPU evidence, not native.

* Chapter trainers: the exported trainer records run through the ROM's own MakeTrainerPokemonParty
  (tools/trainer_party_qualification.generate); species, level, nature, IV/EV, ability and recomputed
  stats are compared with the authored library entries.
* Authored shop: the ROM's special-mart lookup and Mart_Init helpers (tools/mart_qualification).
* Field authority: badge checks and the Surf water prompt still read from this ROM's code.
* Chapter events: each compiled script, read from the exported script archive, holds the expected
  native commands (mart, heal, respawn, badge, tutors, field actions, travel).
* world_readback.check on the exported ROM; the adjacent save is byte-identical to the played save;
  reach from that save over the final project.

Usage: final_readback.py PROJECT ROM SAVE PLAYED_SAVE OUT.json
"""
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / 'tools')]
from sovereign_editor.core import Project  # noqa: E402
from sovereign_editor import (story_authoring as sa, dialogue_format as fmt, script_disasm as sd,  # noqa: E402
                              field_moves as fm, field_services as fs, trainer_format as tf, species as sp,
                              species_forms as sf, world_readback)
from sovereign_editor.formats import digest, resource  # noqa: E402
import mart_qualification as mq  # noqa: E402
import trainer_party_qualification as tq  # noqa: E402

EXPECT = {'ec_clerk': [('callstd', (2011,)), ('holdmsg', ()), ('callstd', (2052,))],
          'ec_healer': [('heal_party', ()), ('set_spawn', (2,))],
          'ec_funds_desk': [('addmoney', (6000,))],
          'ec_leader': [('give_badge', (3,))],
          'ec_trail_guide': [('warp', None)], 'ec_ridge_back': [('warp', None)], 'ec_shortcut': [('warp', None)],
          'ec_ridge_tree': [('hide_person', (0x800D,))], 'ec_ridge_rock': [('hide_person', (0x800D,))],
          'ec_boulder_a': [('strength_flag_action', (1,))], 'ec_boulder_b': [('strength_flag_action', (1,))]}
TUTOR_MOVES = (15, 249, 70, 57)


def main(project_root, rom_path, save_path, played_path, out):
    p = Project(project_root)
    rom = Path(rom_path).read_bytes()
    state = p.composed()
    checks = []

    def check(name, ok, detail=None):
        checks.append({'check': name, 'pass': bool(ok), **({'detail': detail} if detail is not None else {})})

    # Trainers through the ROM's own party generation.
    library = sa.catalog(state, 'trainer')
    for key in ('ranger_01', 'ranger_02', 'ranger_03', 'ranger_04'):
        t = library[key]
        tid = t['trainer_id']
        header, party = resource(rom, 'a/0/5/5', tid)[1], resource(rom, 'a/0/5/6', tid)[1]
        got = tq.generate(rom, tid, header, party)
        ok = got['count'] == len(t['party']) and header[16] == (2 if t.get('battle') == 'double' else 0)
        detail = []
        for want, mon in zip(t['party'], got['mons']):
            first, second, hidden = tf.abilities(p, want['species'], want.get('form', 0))
            ability = {'first': first, 'second': second, 'hidden': hidden}[want.get('ability', 'first')]
            index = sf.personal_index(p, want['species'], want.get('form', 0))
            base = list(sp.decode_personal(resource(rom, 'a/0/0/2', index)[1])['stats'].values())
            stats = [mon['max_hp'], mon['attack'], mon['defense'], mon['speed'], mon['sp_attack'], mon['sp_defense']]
            expect = tq.expected_stats(base, want['level'], want.get('ivs', [0] * 6), want.get('evs', [0] * 6), mon['nature'])
            row_ok = ((mon['species'], mon['level']) == (want['species'], want['level']) and mon['ability'] == ability
                      and stats == expect and ('nature' not in want or mon['nature'] == want['nature'])
                      and ('ivs' not in want or (mon['ivs'], mon['evs']) == (want['ivs'], want['evs'])))
            ok = ok and row_ok
            detail.append({'species': mon['species'], 'level': mon['level'], 'nature': mon['nature'], 'ivs': mon['ivs'],
                           'evs': mon['evs'], 'ability': mon['ability'], 'stats': stats, 'ok': row_ok})
        check(f'trainer {key} (id {tid}) generated by the ROM as authored', ok, detail)
    # Shop.
    index = fs.shop_index(state)['ridge_supplies']
    looked = {r['pokeball_flag']: r['items'] for r in mq.run(mq.memory_from_rom(rom), [index])}
    items = fs.shops(state)['ridge_supplies']
    check(f'special mart {index} lists ridge_supplies (Poké Ball only with flag 0x9A)',
          looked[1] == items and looked[0] == [i for i in items if i != 4], looked)
    # Field authority unchanged.
    try:
        fm.qualify_field_authority(rom); check('field-move badge checks and Surf prompt read from the ROM', True)
    except Exception as exc:                                        # noqa: BLE001
        check('field-move badge checks and Surf prompt read from the ROM', False, str(exc))
    # Compiled chapter scripts.
    ids = sa.allocation(p, state)
    for key, s in sa.catalog(state, 'sequence').items():
        if not key.startswith('ec_') or s['kind'] == 'trainer':
            continue
        raw = resource(rom, fmt.SCRIPT_ARCHIVE, s['script_member'])[1]
        listing = [(n, tuple(a)) for _, (_, n, a, _) in sorted(sd.disassemble(raw, [sd.entries(raw)[ids[key][0] - 1]]).items())]
        want = EXPECT.get(key, [])
        ok = all(any(n == name and (args is None or a == args) for n, a in listing) for name, args in want)
        if key == 'ec_hm_tutor':
            ok = sorted(a[1] for n, a in listing if n == 'move_tutor_init') == sorted(TUTOR_MOVES)
        check(f'compiled script {key} holds its native commands', ok, [n for n, _ in listing][:40])
    # World readback, save identity, reach.
    wr = world_readback.check(rom, p)
    check('world readback of the exported ROM', wr['failed'] == 0, {'passed': wr['passed'], 'failed': wr['failed']})
    check('adjacent save is byte-identical to the played save',
          digest(Path(save_path).read_bytes()) == digest(Path(played_path).read_bytes()), digest(Path(save_path).read_bytes()))
    reach = p.reach(save=played_path)
    chapter = [e for e in reach['events'] if e['event'].startswith('ec_')]
    check('every chapter event reachable from the played save (some after field moves)',
          all(e['reachable'] or e['after_field_moves'] for e in chapter),
          {'direct': [e['event'] for e in chapter if e['reachable']], 'after_field_moves': reach['gated_by_field_moves']})
    result = {'schema': 'sovereign-final-readback-v1', 'rom_sha256': digest(rom), 'project_revision': p.doc['revision'],
              'checks': checks, 'passed': sum(c['pass'] for c in checks), 'failed': sum(not c['pass'] for c in checks),
              'native_acceptance': 'pending (user-run checklist)'}
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text(json.dumps(result, indent=1, default=str))
    print(json.dumps({'passed': result['passed'], 'failed': result['failed'],
                      'failures': [c['check'] for c in checks if not c['pass']]}))


if __name__ == '__main__':
    main(*sys.argv[1:6])
